[package]
name = "rust-studio"
version = "0.1.0"
edition = "2024"
authors = ["Henrique Reimão <henriquerimao@outlook.com>"]
license = "apache-2.0"

[dependencies]
axum = "0.8.4"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["fs"] }
